baseURL = 'https://enorsu.github.io/'
languageCode = 'en-us'
title = 'enorsu.github.io'
theme = "nightfall"




[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[pagination]
pagerSize = 3

[menu]
  [[menu.header]]
    name = "blog"
    weight = 0
    url = "blog"
  [[menu.header]]
    name = "about"
    weight = 1
    url = "about"

[params]
custom_css = ["css/custom.css"]

user = "me"
hostname = "enorsu.github.io"

# You can configure external links to open in new tabs by adding this parameter
openLinksInNewTab = true

displayDateFormat = "1.02.2006"

# Global metadata display settings
# Each can be overridden in individual post frontmatter
showMetadata = true       # Master switch for all metadata display
showPublishedDate = true  # Show published date on post page
showReadingTime = true    # Show reading time on post page
showTags = true           # Show tags on post page
showAuthors = true        # Show authors on post page
showCategories = true     # Show categories on post page

  [params.author]
    name = "enorsu's personal website & blog"  # Website and RSS feed author

[[params.social]]
key = 0
name = "github"
url = "https://github.com/enorsu"
target = "_blank"
aria = "GitHub Profile"

[[params.social]]
key = 0
name = "youtube channel"
url = "https://youtube.com/@enorsu"
target = "_blank"
aria = "YouTube Channel"

[caches]
  [caches.images]
    dir = ':cacheDir/images'